services:
  postgres:
    image: postgres:13
    container_name: postgres-cinema
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinema_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cinema-service:
    build:
      context: .
      dockerfile: ./cmd/Dockerfile
    container_name: cinema-service
    environment:
      POSTGRES_CONNECTION_STRING: postgres://user:password@postgres:5432/cinema_service?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:

